# use zsh as default shell
set-option -g default-shell /bin/zsh

# reload config with prefix+r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# pane/window index starts from 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# show pane index for 10s
set -g display-panes-time 10000

# split panes with | and -  (more intuitive)
unbind '"'
bind | split-window -h
unbind '%'
bind - split-window -v

# vi key bindings in copy mode
set-window-option -g mode-keys vi

# increase scrollback buffer
set -g history-limit 10000

# enable mouse support
set -g mouse on

# reduce escape-time for vim/neovim
set -sg escape-time 10

# status bar
set -g status-interval 5
set -g status-left  "[#S] "
set -g status-right "%Y-%m-%d %H:%M"
